server:
  port: 8080
  servlet:
    context-path: /hoso
    session:
      timeout: 5m
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource:
#    url: jdbc:mysql://120.79.88.98:3306/hosoneu?characterEncoding=utf-8&serverTimezone=GMT%2B8
    #下面的url：@author 29-y 本地数据库地址 @time 2019.06.10
    url: jdbc:mysql://localhost:3306/hoso_local_dev?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.79.88.98
    password: 123456
    port: 6379
mybatis:
  type-aliases-package: edu.neu.hoso.model
  mapper-locations: classpath:mapper/*.xml
